CREATE TABLE user_info (
	id INT(11) PRIMARY KEY AUTO_INCREMENT ,
	user_name VARCHAR(20) DEFAULT NULL ,
	phone VARCHAR(20) DEFAULT NULL ,
	email VARCHAR(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户信息';